<?php

namespace Database\Seeders;

use App\Models\User;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\Storage;
use Takshak\Ashop\Models\Shop\Brand;
use Takshak\Ashop\Models\Shop\Category;
use Takshak\Ashop\Models\Shop\Product;
use Takshak\Ashop\Models\Shop\ProductImage;
use Takshak\Imager\Facades\Picsum;
use Symfony\Component\Console\Helper\ProgressBar;
use Symfony\Component\Console\Output\ConsoleOutput;

class ProductSeeder extends Seeder
{
    public $checkoutTypes = ['checkout', 'query', 'external_url'];
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $productNames = $this->productNames();
        shuffle($productNames);

        // Limit to 100
        $productNames = array_slice($productNames, 0, 100);

        $output = new ConsoleOutput();
        $progressBar = new ProgressBar($output, count($productNames));
        $progressBar->start();

        foreach ($productNames as $productName) {
            $this->product($productName);
            $progressBar->advance();
        }
        $progressBar->finish();
        $output->writeln('');
    }

    public function product($name)
    {
        shuffle($this->checkoutTypes);

        $net_price = rand(10, 99) * 5;
        $sell_price = $net_price - $net_price * (rand(5, 30) / 100);
        $deal_price = $sell_price - $sell_price * (rand(5, 30) / 100);

        $product = new Product();
        $product->name          =  $name;
        $product->subtitle      =  fake()->realText(rand(20, 250));
        $product->brand_id      =  Brand::inRandomOrder()->first()->id;
        $product->sku           =  'ASI' . rand();
        $product->stock         =  rand(10, 250);
        $product->net_price     =  $net_price;
        $product->sell_price    =  $sell_price;
        $product->deal_price    =  $deal_price;
        $product->deal_expiry   =  now()->addDays(rand(5, 25));
        $product->status        =  true;
        $product->featured      =  true;
        $product->info          =  fake()->realText(rand(150, 300));
        $product->checkout_type =  end($this->checkoutTypes);
        $product->user_id       =  User::inRandomOrder()->first()->id;

        $product->slug          = str()->of($product->name)->slug('-') . time();
        $product->image_sm  = 'products/sm/' . $product->slug . '.jpg';
        $product->image_md  = 'products/md/' . $product->slug . '.jpg';
        $product->image_lg  = 'products/' . $product->slug . '.jpg';

        $imgWidth = config('ashop.products.images.width', 800);
        $imgHeight = config('ashop.products.images.height', 900);
        Picsum::dimensions($imgWidth, $imgHeight)
            ->basePath(Storage::disk('public')->path('/'))
            ->save($product->image_lg)
            ->save($product->image_md, $imgWidth / 2)
            ->save($product->image_sm, $imgWidth / 4)
            ->destroy();

        if ($product->checkout_type == 'external_url') {
            $product->external_url = fake()->url();
        }

        $product->save();

        $product->metas()->create([
            'name' => 'm_title',
            'key' => 'product_details',
            'value' => fake()->realText(rand(50, 150)),
        ]);
        $product->metas()->create([
            'name' => 'm_keywords',
            'key' => 'product_details',
            'value' => fake()->realText(rand(50, 150)),
        ]);
        $product->metas()->create([
            'name' => 'm_description',
            'key' => 'product_details',
            'value' => fake()->realText(rand(50, 150)),
        ]);
        $product->metas()->create([
            'name' => 'description',
            'key' => 'product_details',
            'value' => fake()->realText(rand(500, 3000)),
        ]);

        $categories = Category::with('attributes')->inRandomOrder()->limit(rand(1, 5))->get();
        $product->categories()->sync($categories->pluck('id'));

        foreach ($categories->pluck('attributes')->collapse() as $attribute) {
            $product->metas()->create([
                'key' => 'product_attributes',
                'name' => $attribute->name,
                'value' => collect($attribute->options)
                    ->shuffle()
                    ->take(rand(1, count($attribute->options)))
                    ->toJson(),
            ]);
        }

        for ($j = 0; $j < rand(1, 10); $j++) {
            $productImage = new ProductImage();
            $productImage->product_id = $product->id;
            $productImage->title = $product->name;

            $fileName = str()->of(microtime())->slug('-') . '.jpg';
            $productImage->image_lg = 'products/' . $fileName;
            $productImage->image_md = 'products/md/' . $fileName;
            $productImage->image_sm = 'products/sm/' . $fileName;

            $imgWidth = config('shopze.products.images.width', 800);
            $imgHeight = config('shopze.products.images.height', 900);
            Picsum::dimensions($imgWidth, $imgHeight)
                ->basePath(Storage::disk('public')->path('/'))
                ->save($productImage->image_lg)
                ->save($productImage->image_md, $imgWidth / 2)
                ->save($productImage->image_sm, $imgWidth / 4)
                ->destroy();

            $productImage->save();
        }

        return $product;
    }

    public function productNames()
    {
        return  [
            'LEGO City Police Station',
            'LEGO Star Wars Millennium Falcon',
            'LEGO Friends Heartlake City Resort',
            'LEGO Technic Bugatti Chiron',
            'LEGO Harry Potter Hogwarts Castle',
            'Hasbro Nerf N-Strike Elite Disruptor',
            'Hasbro Monopoly Classic Board Game',
            'Hasbro Play-Doh Fun Factory Set',
            'Hasbro Mr. Potato Head Classic',
            'Hasbro Transformers Optimus Prime',
            'Mattel Barbie Dreamhouse',
            'Mattel Hot Wheels Ultimate Garage',
            'Mattel Fisher-Price Laugh & Learn Smart Stages Chair',
            'Mattel UNO Card Game',
            'Mattel Matchbox Superfast Cars',
            'Fisher-Price Little People Animal Rescue',
            'Fisher-Price Rock-a-Stack',
            'Fisher-Price Imaginext Batcave',
            'Fisher-Price Baby’s First Blocks',
            'Fisher-Price Laugh & Learn Smart Phone',
            'Nerf Elite 2.0 Shockwave RD-15 Blaster',
            'Nerf Super Soaker Hydra Water Blaster',
            'Nerf Rival Kronos XVIII-500',
            'Nerf Fortnite TS-R Blaster',
            'Nerf Zombie Strike FlipFury Blaster',
            'Hot Wheels Monster Trucks 5-Pack',
            'Hot Wheels Track Builder Starter Kit',
            'Hot Wheels City Ultimate Garage',
            'Hot Wheels Super Loop Chase Race Track Set',
            'Hot Wheels Stunt & Splash Car Wash',
            'Playmobil Pirate Ship',
            'Playmobil City Life Modern House',
            'Playmobil Police Station with Jail',
            'Playmobil Family Camping Trip',
            'Playmobil Space Shuttle',
            'Melissa & Doug Wooden Building Blocks Set',
            'Melissa & Doug Deluxe Magic Set',
            'Melissa & Doug Plush Giraffe',
            'Melissa & Doug Wooden Train Set',
            'Melissa & Doug Magnetic Dress-Up Dolls',
            'VTech KidiZoom Smartwatch DX2',
            'VTech Sit-to-Stand Learning Walker',
            'VTech Write & Learn Creative Center',
            'VTech Spin & Learn Color Flashlight',
            'VTech Kidizoom Camera Pix',
            'LeapFrog My First Learning Tablet',
            'LeapFrog 100 Animals Book',
            'LeapFrog LeapStart 3D Interactive Learning System',
            'LeapFrog LeapReader System',
            'LeapFrog Scout and Violet 100 Words Book',
            'Crayola Inspiration Art Case',
            'Crayola Color Wonder Mess-Free Coloring Kit',
            'Crayola Ultimate Light Board',
            'Crayola Washable Kids Paint Set',
            'Crayola Silly Scents Marker Set',
            'Disney Princess Royal Shimmer Dolls',
            'Disney Pixar Cars Lightning McQueen',
            'Disney Frozen 2 Elsa Doll',
            'Disney Junior Mickey Mouse Clubhouse Playset',
            'Disney Toy Story Buzz Lightyear Action Figure',
            'Mega Bloks First Builders Big Building Bag',
            'Mega Bloks Building Basics ABC Learning Train',
            'Mega Bloks Thomas & Friends Engine Set',
            'Mega Bloks Paw Patrol Rescue Tower',
            'Mega Bloks Jeep Ride-On Vehicle',
            'Funko Pop! Marvel Avengers Iron Man',
            'Funko Pop! Star Wars The Mandalorian',
            'Funko Pop! Harry Potter Hermione Granger',
            'Funko Pop! DC Comics Batman',
            'Funko Pop! Disney The Lion King Simba',
            'Little Tikes Cozy Coupe Ride-On Car',
            'Little Tikes Easy Store Water Table',
            'Little Tikes Princess Cottage Playhouse',
            'Little Tikes 3-in-1 Sports Zone',
            'Little Tikes Trampoline',
            'Transformers Cyberverse Optimus Prime',
            'Transformers Bumblebee Action Figure',
            'Transformers Earthrise Megatron',
            'Transformers Siege Starscream',
            'Transformers Cyberverse Grimlock',
            'Paw Patrol Ultimate Rescue Fire Truck',
            'Paw Patrol Chase’s Deluxe Cruiser',
            'Paw Patrol Skye’s Helicopter',
            'Paw Patrol Lookout Tower Playset',
            'Paw Patrol Dino Rescue Motorized Vehicle',
            'Play-Doh Kitchen Creations Ultimate Ice Cream Truck',
            'Play-Doh Fun Tub',
            'Play-Doh Slime Variety Pack',
            'Play-Doh Modeling Compound Rainbow Pack',
            'Play-Doh Crazy Cuts Hair Salon',
            'Schleich Horse Club Riding Center',
            'Schleich Wild Life Animal Rescue Truck',
            'Schleich Farm World Large Red Barn',
            'Schleich Dinosaurs Volcano Expedition Base Camp',
            'Schleich Bayala Unicorns Playset',
            'Tonka Steel Classics Mighty Dump Truck',
            'Tonka Classic Steel Front Loader',
            'Tonka Classic Mighty Crane',
            'Tonka Toughest Mighty Dump Truck',
            'Tonka Steel Excavator Vehicle',
            'Ty Beanie Babies Classic Bear',
            'Ty Flippables Sparkle Sequin Plush Penguin',
            'Ty Beanie Boos Owl Plush',
            'Ty Flippables Unicorn Plush',
            'Ty Beanie Boos Giraffe Plush',
            'L.O.L. Surprise! O.M.G. Fashion Dolls',
            'L.O.L. Surprise! Remix Super Surprise',
            'L.O.L. Surprise! Present Surprise',
            'L.O.L. Surprise! Lights Glitter Doll',
            'L.O.L. Surprise! Boys Series 4',
            'American Girl Truly Me Doll',
            'American Girl WellieWishers Ashlyn Doll',
            'American Girl Blaire Wilson Doll',
            'American Girl Courtney Doll',
            'American Girl Bitty Baby Doll',
            'Spin Master Hatchimals CollEGGtibles 12-Pack',
            'Spin Master Air Hogs Supernova',
            'Spin Master Kinetic Sand Sandbox Set',
            'Spin Master Bakugan Starter Pack',
            'Spin Master Zoomer Playful Pup',
            'K’NEX 100 Model Building Set',
            'K’NEX Ferris Wheel Building Set',
            'K’NEX Thrill Rides Roller Coaster Building Set',
            'K’NEX Imagine Power and Play Motorized Building Set',
            'K’NEX Bionic Blast Roller Coaster Building Set',
            'Bandai Dragon Ball Super Action Figures',
            'Bandai Tamagotchi On Virtual Pet',
            'Bandai Godzilla King of Monsters Action Figure',
            'Bandai Gundam Universe RX-78-2 Action Figure',
            'Bandai Naruto Shippuden Action Figures',
            'Baby Alive Sweet Spoonfuls Baby Doll',
            'Baby Alive Magical Mixer Baby Doll',
            'Baby Alive Baby Shark Doll',
            'Baby Alive Littles Baby Doll',
            'Baby Alive Real As Can Be Baby Doll',
            'Thomas & Friends TrackMaster Motorized Railway',
            'Thomas & Friends Wood Thomas and Friends Train Set',
            'Thomas & Friends Adventures Steelworks Thomas',
            'Thomas & Friends Turbo Thomas',
            'Thomas & Friends Super Station',
            'KidKraft Ultimate Corner Play Kitchen Set',
            'KidKraft Vintage Kitchen',
            'KidKraft Wooden Dollhouse',
            'KidKraft Building Bricks Play N Store Table',
            'KidKraft Fire Station Set',
            'Radio Flyer My First Scooter',
            'Radio Flyer Classic Tricycle',
            'Radio Flyer All-Terrain Wagon',
            'Radio Flyer Deluxe Steer & Stroll Trike',
            'Radio Flyer Little Red Roadster',
            'Meccano Erector Super Construction Set',
            'Meccano Robot Building Set',
            'Meccano Meccasaur Robot',
            'Meccano 25-in-1 Motorized Building Set',
            'Meccano Micronoid Robot',
            'Calico Critters Townhome Gift Set',
            'Calico Critters Adventure Treehouse',
            'Calico Critters Red Roof Cozy Cottage',
            'Calico Critters Baby Castle Nursery',
            'Calico Critters Luxury Townhome',
            'Brio My First Railway Beginner Pack',
            'Brio World Cargo Transport Helicopter',
            'Brio World Metro Railway Set',
            'Brio World Smart Tech Sound Action Tunnel Set',
            'Brio World Firefighter Helicopter',
            'Hexbug Nano Robotic Creatures',
            'Hexbug BattleBots Arena',
            'Hexbug VEX Robotics Zip Flyer',
            'Hexbug Spider',
            'Hexbug VEX Robotics Catapult',
            'Hape Pound & Tap Bench',
            'Hape All-in-One Easel',
            'Hape Mighty Mountain Mine',
            'Hape Wooden Toy Kitchen',
            'Hape Quadrilla Wooden Marble Run',
            'WowWee Fingerlings Baby Monkey',
            'WowWee Robosapien X Robot',
            'WowWee Mip Arcade Robot',
            'WowWee Chippies Robot Toy Dog',
            'WowWee Elmoji Junior Coding Robot',
            'Step2 Rain Showers Splash Pond Water Table',
            'Step2 Whisper Ride II Ride-On',
            'Step2 All Around Playtime Patio',
            'Step2 Skyward Summit Climber',
            'Step2 Wagon for Two Plus',
            'TOMY John Deere Tractor Toy Set',
            'TOMY Hide & Squeak Eggs',
            'TOMY Toomies Spin & Splash Octopals Bath Toy',
            'TOMY Pop-Up Pirate Game',
            'TOMY Aquadoodle Drawing Mat',
            'Moose Toys Treasure X Sunken Gold Shark’s Treasure',
            'Moose Toys Bluey Family Home Playset',
            'Moose Toys Heroes of Goo Jit Zu Action Figures',
            'Moose Toys Scruff-a-Luvs',
            'Moose Toys Real Littles Shopkins',
            'Ravensburger Disney Villainous Board Game',
            'Ravensburger GraviTrax Starter Set Marble Run',
            'Ravensburger Labyrinth Board Game',
            'Ravensburger Harry Potter Jigsaw Puzzle',
            'Ravensburger 3D Puzzle Eiffel Tower',
            'Jakks Pacific Big-Figs Star Wars Darth Vader',
            'Jakks Pacific Super Mario Action Figures',
            'Jakks Pacific Disney Frozen Snow Glow Elsa Doll',
            'Jakks Pacific DC Comics Batman Big-Fig',
            'Jakks Pacific Tsum Tsum Plush Toy Set',
            'Siku World Construction Site Set',
            'Siku 3-Pack Die-Cast Vehicles',
            'Siku Remote Control John Deere Tractor',
            'Siku Racing Set with Ferrari & Lamborghini',
            'Siku Die-Cast Crane Truck',
            'Sylvanian Families Red Roof Country Home',
            'Sylvanian Families Deluxe Living Room Set',
            'Sylvanian Families Seaside Cruiser House Boat',
            'Sylvanian Families Supermarket Set',
            'Sylvanian Families Baby Nursery Set',
            'My Little Pony Princess Twilight Sparkle',
            'My Little Pony Rainbow Dash Figure',
            'My Little Pony Rarity Fashion Playset',
            'My Little Pony Pinkie Pie’s Rainbow Helicopter',
            'My Little Pony Equestria Girls Fluttershy',
            'Magformers Magnetic Building Set',
            'Magformers Creator Set',
            'Magformers Deluxe Rainbow Set',
            'Magformers Wow Set',
            'Magformers Carnival Set',
            'Ouaps Oops Play House',
            'Ouaps Oh, la petite ferme!',
            'Ouaps BabyCroc Musical Mobile',
            'Ouaps Cotoons Bath Island',
            'Ouaps Oops Sunny Day Mat',
            'Beyblade Burst Rise Hypersphere Set',
            'Beyblade Burst Turbo Slingshock Rail Set',
            'Beyblade Burst Evolution SwitchStrike Set',
            'Beyblade Burst Rise Starter Pack',
            'Beyblade Burst Pro Series Elite Champions Pro Set',
            'Peppa Pig Peppa’s Big Red Car',
            'Peppa Pig Peppa’s Family Home Playset',
            'Peppa Pig Peppa’s Adventure Boat',
            'Peppa Pig Peppa’s Deluxe House',
            'Peppa Pig Peppa’s Camper Van Playset',
            'LeapFrog RockIt Twist Handheld Learning Game System',
            'LeapFrog LeapPad Ultimate Learning Tablet',
            'LeapFrog LeapFrog LeapBuilders ABC Smart House',
            'LeapFrog 2-in-1 LeapTop Touch Laptop',
            'LeapFrog LeapStart 3D Learning System',
            'VTech Kidizoom Smartwatch DX3',
            'VTech KidiBuzz 3 Smart Device for Kids',
            'VTech Touch & Learn Activity Desk Deluxe',
            'VTech Explore and Write Activity Desk',
            'VTech Go! Go! Smart Wheels Ultimate Track Set',
            'Hatchimals WOW Llalacorn Interactive Pet',
            'Hatchimals CollEGGtibles Cosmic Candy 12-Pack',
            'Hatchimals Pixies Crystal Flyers',
            'Hatchimals HatchiBabies',
            'Hatchimals CollEGGtibles Secret Surprise Playset',
            'Little Live Pets Gotta Go Flamingo',
            'Little Live Pets Lil’ Dippers Fish Tank Playset',
            'Little Live Pets Scruff-a-Luvs Real Rescue',
            'Little Live Pets Cozy Dozy Koala',
            'Little Live Pets OMG Pets Interactive Puppy',
            'PJ Masks PJ Seeker Vehicle Playset',
            'PJ Masks Deluxe Gekko-Mobile',
            'PJ Masks HQ Rocket with Lights and Sounds',
            'PJ Masks Catboy’s Cat-Car',
            'PJ Masks Super Moon Adventure Set',
            'SpongeBob SquarePants Pineapple House Playset',
            'SpongeBob SquarePants Action Figures 5-Pack',
            'SpongeBob SquarePants Plankton’s Revenge Set',
            'SpongeBob SquarePants Patrick Star Plush',
            'SpongeBob SquarePants Krusty Krab Playset',
            'Frozen 2 Elsa’s Ice Palace Playset',
            'Frozen 2 Singing Elsa Doll',
            'Frozen 2 Sven Plush Toy',
            'Frozen 2 Olaf’s Frozen Adventure Playset',
            'Frozen 2 Enchanted Forest Playset',
            'Barbie Dreamplane Playset',
            'Barbie Travel Doll with Accessories',
            'Barbie Dreamtopia Princess Doll',
            'Barbie Color Reveal Doll',
            'Barbie Fashionistas Doll',
            'Thomas & Friends Motorized Railway Hyper Glow Set',
            'Thomas & Friends Talking Diesel Engine',
            'Thomas & Friends Super Cruiser Playset',
            'Thomas & Friends TrackMaster Bridge Lift Set',
            'Thomas & Friends Nia & the Elephant Engine',
            'Disney Pixar Toy Story 4 Woody Doll',
            'Disney Pixar Toy Story 4 Buzz Lightyear Figure',
            'Disney Pixar Toy Story 4 Forky Plush',
            'Disney Pixar Toy Story 4 Duke Caboom Stunt Set',
            'Disney Pixar Toy Story 4 Jessie’s Roundup Set',
            'L.O.L. Surprise! Hairgoals Makeover Series',
            'L.O.L. Surprise! Winter Disco Chalet Doll House',
            'L.O.L. Surprise! O.M.G. Remix Super Surprise Set',
            'L.O.L. Surprise! Glitter Globe Winter Disco',
            'L.O.L. Surprise! All-Star B.B.s Sports Series',
            'Transformers Cyberverse Adventures Action Figures',
            'Transformers Earthrise War for Cybertron Trilogy',
            'Transformers Studio Series Action Figures',
            'Transformers Generations Selects Action Figures',
            'Transformers BotBots Collectibles',
            'Playmobil Country Pony Farm Set',
            'Playmobil Wild Life Animal Rescue Truck',
            'Playmobil City Life Family Home',
            'Playmobil City Action Fire Truck',
            'Playmobil 123 Take Along Fire Station',
            'Mega Bloks Paw Patrol Chase’s Patrol Cruiser',
            'Mega Bloks First Builders Big Building Bag Pink',
            'Mega Bloks Wonder Builders Large Building Bag',
            'Mega Bloks Call of Duty Desert Outpost',
            'Mega Bloks Halo Warthog Rally',
            'Funko Pop! Harry Potter Albus Dumbledore Figure',
            'Funko Pop! Star Wars Baby Yoda (The Child)',
            'Funko Pop! DC Comics Wonder Woman',
            'Funko Pop! Marvel Black Panther',
            'Funko Pop! Disney Moana and Pua',
            'LEGO Marvel Avengers Iron Man Mech',
            'LEGO Marvel Spider-Man Monster Truck vs. Mysterio',
            'LEGO Disney Frozen Elsa’s Jewelry Box',
            'LEGO City Ocean Exploration Ship',
            'LEGO Super Mario Adventures with Mario Starter Course',
            'Fisher-Price Thomas & Friends Talking Thomas Engine',
            'Fisher-Price Laugh & Learn Smart Stages Puppy',
            'Fisher-Price Imaginext Jurassic World Dinosaur Playset',
            'Fisher-Price Little People Caring for Animals Farm',
            'Fisher-Price Rock-a-Stack with Lights & Music',
            'Mattel Jurassic World Epic Roarin’ Tyrannosaurus Rex',
            'Mattel Hot Wheels Color Shifters Sharkport Showdown',
            'Mattel Barbie Malibu House Playset',
            'Mattel Polly Pocket Big Pocket World',
            'Mattel WWE Championship Belt',
            'Hasbro Star Wars The Black Series Mandalorian Action Figure',
            'Hasbro Marvel Legends Series Iron Man Action Figure',
            'Hasbro Monopoly Junior Board Game',
            'Hasbro Play-Doh Kitchen Creations Burger Barbecue Set',
            'Hasbro Nerf Ultra One Motorized Blaster',
            'Tonka Classic Steel Mighty Dump Truck',
            'Tonka Steel Trencher Vehicle',
            'Tonka Classic Bulldozer',
            'Tonka Metal Movers Combo Pack',
            'Tonka Classic Steel Front Loader',
            'Schleich Dinosaurs Giganotosaurus Figure',
            'Schleich Wild Life Jungle Animal Set',
            'Schleich Farm World Starter Set',
            'Schleich Horse Club Hannah’s First Aid Kit Playset',
            'Schleich Eldrador Creatures Lava Dragon Figure',
            'KidKraft Chelsea Doll Cottage',
            'KidKraft Uptown Espresso Kitchen',
            'KidKraft Waterfall Mountain Train Set and Table',
            'KidKraft Let’s Cook Wooden Play Kitchen',
            'KidKraft Majestic Mansion Dollhouse',
            'Radio Flyer 4-in-1 Stroll ‘N Trike',
            'Radio Flyer Pathfinder Wagon',
            'Radio Flyer Classic Bumper Car',
            'Radio Flyer Blaze Interactive Ride-On Horse',
            'Radio Flyer My 1st Wagon',
            'Spin Master Kinetic Sand Sandisfying Set',
            'Spin Master Air Hogs Zero Gravity Laser Wall Racer',
            'Spin Master Paw Patrol Mighty Pups Super Paws Jet',
            'Spin Master Hatchimals Pixies Riders',
            'Spin Master Etch A Sketch Freestyle',
            'Moose Toys Scruff-a-Luvs Babies Mystery Rescue Pet',
            'Moose Toys Treasure X Aliens Ultimate Dissection Kit',
            'Moose Toys Heroes of Goo Jit Zu Dino Power Action Figures',
            'Moose Toys Little Live OMG Pets Rescue Pet',
            'Moose Toys Bluey School Playset',
            'TOMY John Deere Sandbox Vehicle Set',
            'TOMY John Deere Build-A-Buddy Johnny Tractor',
            'TOMY Toomies Hide & Squeak Eggs',
            'TOMY Lamaze Freddie The Firefly',
            'TOMY Aquadoodle Classic Drawing Mat',
            'Hexbug BattleBots Rivals 2.0',
            'Hexbug Nano Nitro Slingshot',
            'Hexbug VEX Robotics Battlebots Arena',
            'Hexbug Scarab Robotic Bug',
            'Hexbug Nitro Circus Stunt Set',
            'Hape Pound & Tap Bench with Xylophone',
            'Hape Walk-A-Long Snail Shape Sorter',
            'Hape Kid’s Wooden Toy Ukulele',
            'Hape Wooden Toy Train Set',
            'Hape Quadrilla Wooden Marble Run Castle Set',
            'Hape Playful Piano Musical Toy',
            'Hape Gourmet Play Kitchen',
            'Hape Wooden Ice Cream Station',
            'WowWee Fingerlings Glitter Monkey',
            'WowWee Baby Shark Official Song Puppet',
            'WowWee Roboraptor X Dinosaur',
            'WowWee Fingerlings Untamed Dragon',
            'WowWee CHiP Robot Toy Dog',
            'WowWee Pinkfong Baby Shark Dancing Doll',
            'Step2 Hot Wheels Toddler to Twin Bed',
            'Step2 Ride Along Wagon',
            'Step2 Deluxe Art Master Desk',
            'Step2 Playhouse Climber & Slide',
            'Step2 Push Around Buggy Ride-On',
            'TOMY Gearation Magnetic Moving Gears',
            'TOMY John Deere Sit-N-Scoot Tractor',
            'TOMY Toomies Hide & Squeak Nesting Eggs',
            'TOMY Pic ‘N’ Pop Push Toy',
            'TOMY Lamaze Octotunes Musical Toy',
            'Playmobil Knights Castle Fortress',
            'Playmobil Rescue Ambulance',
            'Playmobil Mars Space Station',
            'Playmobil Dragon’s Lair',
            'Playmobil Family Fun Aquarium',
            'Playmobil Police Headquarters with Prison',
            'Spin Master Monster Jam Mega Grave Digger',
            'Spin Master Etch A Sketch Classic',
            'Spin Master Hatchimals Pixie Riders Crystal Flyers',
            'Spin Master Air Hogs Extreme Air Board Stunt Kite',
            'Spin Master Meccano Supercar Building Set',
            'LeapFrog LeapReader Learn to Read Mega Pack',
            'LeapFrog LeapStart Preschool Success Bundle',
            'LeapFrog Scout’s Learning Lights Remote',
            'LeapFrog LeapBuilders 123 Counting Train',
            'LeapFrog Number Lovin’ Oven',
            'VTech Kidizoom Creator Cam',
            'VTech Go! Go! Smart Wheels Spinning Spiral Tower',
            'VTech Musical Rhymes Book',
            'VTech Drill & Learn Toolbox',
            'VTech PJ Masks Super Gekko Learning Watch',
            'LEGO Ninjago Spinjitzu Slam – Jay',
            'LEGO Creator 3-in-1 Pirate Ship',
            'LEGO Harry Potter Hogwarts Express Train',
            'LEGO Technic Off-Road Buggy',
            'LEGO Friends Summer Water Park',
            'Fisher-Price Deluxe Kick & Play Piano Gym',
            'Fisher-Price Linkimals Smooth Moves Sloth',
            'Fisher-Price Soothe & Glow Seahorse',
            'Fisher-Price Laugh & Learn Smart Home',
            'Fisher-Price Little People Travel Together Airplane',
            'Mattel Hot Wheels Monster Trucks Stunt Tire Playset',
            'Mattel Barbie Dream Camper',
            'Mattel Hot Wheels Corkscrew Crash Track Set',
            'Mattel Polly Pocket Flamingo Floatie Compact',
            'Mattel Masters of the Universe Origins Castle Grayskull',
            'Hasbro Star Wars The Mandalorian Darksaber',
            'Hasbro Play-Doh Wheels Firetruck Toy',
            'Hasbro My Little Pony Princess Celestia Figure',
            'Hasbro Marvel Legends Spider-Man Action Figure',
            'Hasbro Nerf Ultra Select Motorized Blaster',
            'Ty Beanie Boos Kiki Grey Cat Plush',
            'Ty Squish-a-Boos Dotty the Leopard Plush',
            'Ty Flippables Malibu the Pink Sequin Dolphin Plush',
            'Ty Beanie Babies Peanut the Elephant Plush',
            'Ty Beanie Boos Owlette the Owl Plush',
            'Mega Bloks Call of Duty WWII Battle Pack',
            'Mega Bloks Minions Fart ‘n Fire Building Set',
            'Mega Bloks Wonder Builders 150-Piece Building Set',
            'Mega Bloks Fast Tracks Racing Set',
            'Mega Bloks Build ‘n Learn Table',
            'Disney Princess Royal Horse and Carriage',
            'Disney Pixar The Incredibles Family Action Figures',
            'Disney Frozen 2 Anna Adventure Doll',
            'Disney Cars Lightning McQueen Remote Control Car',
            'Disney Mickey Mouse Talking Action Figure',
            'Tonka Steel Classic Trencher Truck',
            'Tonka Mighty Motorized Garbage Truck',
            'Tonka Classic Fire Engine Truck',
            'Tonka Monster Metal Movers Construction Set',
            'Tonka Steel Grader Vehicle',
            'Schleich Wild Life Crocodile Jungle Research Station',
            'Schleich Horse Club Sarah’s Camping Adventure',
            'Schleich Dinosaurs Large Skull Trap',
            'Schleich Farm World Mobile Vet Clinic',
            'Schleich Eldrador Creatures Lava Scorpion',
            'KidKraft Everyday Heroes Wooden Play Set',
            'KidKraft So Chic Dollhouse',
            'KidKraft Adventure Bound Space Shuttle',
            'KidKraft Wooden Nativity Play Set',
            'KidKraft Lil’ Doll Cradle',
            'Ravensburger Minecraft Builders & Biomes Strategy Game',
            'Ravensburger Disney Frozen 2 Puzzle 1000 Pieces',
            'Ravensburger GraviTrax Expansion Set',
            'Ravensburger Harry Potter Labyrinth Board Game',
            'Ravensburger Eiffel Tower Night Edition 3D Puzzle',
            'Hape Gourmet Play Kitchen Starter Set',
            'Hape Double-Sided Wooden Easel',
            'Hape Junior Inventor Science Experiment Toolbox',
            'Hape All Season Wooden Dollhouse',
            'Hape Jungle Wooden Marble Run',
            'Melissa & Doug Let’s Play House Dust, Sweep & Mop Set',
            'Melissa & Doug Giant Stuffed Giraffe',
            'Melissa & Doug Fresh Mart Grocery Store',
            'Melissa & Doug Farm Animals Puzzle Set',
            'Melissa & Doug Wooden Pizza Party Play Food Set',
            'Crayola Ultimate Crayon Collection',
            'Crayola Light-Up Tracing Pad',
            'Crayola Scribble Scrubbie Pets Salon Playset',
            'Crayola Glitter Dots Sparkle Station Craft Kit',
            'Crayola Washable Sidewalk Chalk',
            'Little Tikes T-Ball Set',
            'Little Tikes Spiralin’ Seas Waterpark Play Table',
            'Little Tikes Easy Score Basketball Set',
            'Little Tikes Gas ‘n Go Mower',
            'Little Tikes Cozy Coupe Dino Ride-On',
            'Brio World Railway Starter Set',
            'Brio Firefighter Helicopter',
            'Brio Magnetic Bell Signal',
            'Brio Travel Switching Train Station',
            'Brio Smart Tech Sound Action Tunnel Circle Set',
            'Calico Critters Baby Ferris Wheel',
            'Calico Critters Adventure Treehouse Gift Set',
            'Calico Critters Grand Department Store',
            'Calico Critters Red Roof Cozy Cottage Starter Home',
            'Calico Critters Sunshine Nursery Bus',
            'Hexbug Robotic Soccer Arena',
            'Hexbug Nano Flash Playground',
            'Hexbug BattleBots Minotaur and Beta',
            'Hexbug VEX Robotics Construction Zone',
            'Hexbug Scarab XL Robotic Bug',
            'Step2 Unicorn Up & Down Roller Coaster',
            'Step2 Naturally Playful Sand & Water Table',
            'Step2 Ball Buddies Adventure Center',
            'Step2 Deluxe Canyon Road Train & Track Table',
            'Step2 Play & Shade Pool',
            'Moose Toys Treasure X Kings Gold Treasure Tomb',
            'Moose Toys Little Live Pets Scruff-a-Luvs Snow Pals',
            'Moose Toys Shopkins Real Littles Mega Pack',
            'Moose Toys Heroes of Goo Jit Zu Galaxy Attack',
            'Moose Toys Bluey Heeler Family Home',
            'TOMY Lamaze Stack & Play Toy Rings',
            'TOMY Toomies Sort & Pop Spinning UFO',
            'TOMY John Deere Animal Sounds Hayride',
            'TOMY Lamaze Clip & Go Captain Calamari',
            'TOMY Aquadoodle Drawing Mat',
            'Playmobil Porsche 911 Carrera S',
            'Playmobil Country Horseback Riding Lessons',
            'Playmobil City Action Fire Engine with Lights and Sound',
            'Playmobil Family Fun Zoo Playset',
            'Playmobil Space Rocket with Launch Site',
            'Hape Wooden Puppet Theater',
            'Hape Activity Walker',
            'Hape Toot-Toot Drivers Garage',
            'Hape Wooden Toy Shape Sorter',
            'Hape Marble Run Super Set',
            'Melissa & Doug Wooden Toy Grocery Store',
            'Melissa & Doug Magnetic Calendar',
            'Melissa & Doug Folding Princess Castle',
            'Melissa & Doug Wooden Birthday Cake',
            'Melissa & Doug Pattern Blocks and Boards',
            'Fisher-Price Little People Take Turns Skyway',
            'Fisher-Price Laugh & Learn Smart Stages Piggy Bank',
            'Fisher-Price Imaginext Superfriends Batcave',
            'Fisher-Price Little People Big Helpers Home',
            'Fisher-Price Laugh & Learn Around the Town Learning Table',
            'VTech Baby Babble & Sing Monkey',
            'VTech Little Apps Tablet',
            'VTech Touch and Learn Activity Desk',
            'VTech Baby\'s Learning Laptop',
            'VTech Kidizoom Duo Selfie Camera',
            'LEGO City Police Station Building Kit',
            'LEGO City Road Plates Set',
            'LEGO Creator 3-in-1 Pirate Ship Building Set',
            'LEGO Creator Expert Roller Coaster',
            'LEGO Friends Olivia’s Tree House',
            'Hot Wheels Ultimate Garage Playset',
            'Hot Wheels Track Builder Stunt Box',
            'Hot Wheels Monster Trucks Epic Loop Challenge',
            'Hot Wheels Car Wash Playset',
            'Hot Wheels Race Ace Transporter',
            'Playmobil 1.2.3 Adventure Car with Horse Trailer',
            'Playmobil Back to the Future DeLorean',
            'Playmobil City Action Police Car with Lights',
            'Playmobil Dragon Knights Fortress',
            'Playmobil Country Barn with Animals',
            'Schleich Farm World Farm House',
            'Schleich Dinosaurs Velociraptor',
            'Schleich Wildlife Lion Figure',
            'Schleich Horse Club Horse & Rider Set',
            'Schleich Eldrador Creatures Ice Dragon',
            'Calico Critters Baby Playground Set',
            'Calico Critters Cozy Cottage Starter Home',
            'Calico Critters Red Roof Country Home',
            'Calico Critters Sweets Bakery Set',
            'Calico Critters Town Series Family Pack',
            'TOMY Thomas & Friends TrackMaster Remote Control Thomas',
            'TOMY John Deere Tractor with Front Loader',
            'TOMY Toomies Fluffy the Dog',
            'TOMY Aquadoodle Magic Mat',
            'TOMY Dino Transporter Playset',
            'Spin Master Kinetic Sand Beach Sand Kingdom',
            'Spin Master Etch A Sketch Magic Screen',
            'Spin Master Paw Patrol Rescue Knights Chase',
            'Spin Master Monster Jam Grave Digger',
            'Spin Master Meccano Supercar Builder Set',
            'Fisher-Price Laugh & Learn Smart Stages Puppy',
            'Fisher-Price Imaginext Dinosaurs T-Rex',
            'Fisher-Price Little People Farm Animal Friends',
            'Fisher-Price Laugh & Learn Smart Stages Chair',
            'Fisher-Price Little People Animal Friends Farm',
            'Hasbro Star Wars The Clone Wars Anakin Skywalker',
            'Hasbro Marvel Avengers Iron Man Mark LXXXV',
            'Hasbro My Little Pony Rarity’s Boutique',
            'Hasbro Monopoly Classic Game',
            'Hasbro Nerf Fortnite SP-L Elite Dart Blaster',
            'Crayola Inspiration Art Case',
            'Crayola Super Tips Markers Set',
            'Crayola Crayons 64 Count',
            'Crayola Washable Markers 10 Count',
            'Crayola Scribble Scrubbie Pets Color-In Activity',
            'Step2 Naturally Playful Sand & Water Table',
            'Step2 Play & Shade Pool',
            'Step2 Water Wheel Play Table',
            'Step2 Choo Choo Wagon',
            'Step2 All Around Playtime Patio with Canopy',
            'L.O.L. Surprise! OMG Fashion Dolls',
            'L.O.L. Surprise! Hairgoals Series',
            'L.O.L. Surprise! Clubhouse Playset',
            'L.O.L. Surprise! Winter Disco Ball',
            'L.O.L. Surprise! All-Star B.B.s Doll',
            'Moose Toys Real Littles Frozen Treats',
            'Moose Toys Heroes of Goo Jit Zu Dino Power',
            'Moose Toys Little Live Pets Squirrel',
            'Moose Toys Scruff-a-Luvs Cuties',
            'Moose Toys Treasure X Legends',
            'HEXBUG Nano with Habitat Set',
            'HEXBUG VEX Robotics Building Set',
            'HEXBUG BattleBots Rival Doombah',
            'HEXBUG Scarab Robot',
            'HEXBUG Fire Ant',
            'TOMY John Deere Big Scoop Dump Truck',
            'TOMY Toomies Push Along Snail',
            'TOMY Aquadoodle Magic Mat',
            'TOMY Lamaze Freddie the Firefly',
            'TOMY Gearation Gear Building Set',
            'Brio Classic Railway Starter Set',
            'Brio My First Railway Starter Set',
            'Brio Push-Along Dog',
            'Brio Adventure Railway Set',
            'Brio My First Take Along Train Set',
            'KidKraft Deluxe Activity Cube',
            'KidKraft Superhero Play Set',
            'KidKraft Pirate Ship Play Set',
            'KidKraft Firehouse Play Set',
            'KidKraft Fairy-tale Castle Play Set',
            'Hape Create & Learn Music Set',
            'Hape Piano Play and Learn',
            'Hape Wooden Kids Maracas',
            'Hape First Play Rainbow Xylophone',
            'Hape Musical Rainbow Stacker',
            'LEGO Disney Princess Belle’s Castle',
            'LEGO Star Wars Millennium Falcon',
            'LEGO Ninjago Legacy Kai’s Fire Dragon',
            'LEGO Friends Emma’s Art Studio',
            'LEGO City Monster Truck',
            'Moose Toys Little Live Pets Light Up Unicorn',
            'Moose Toys Scruff-a-Luvs Real Rescue',
            'Moose Toys Real Littles Shopkins',
            'Moose Toys Heroes of Goo Jit Zu - Superhero Edition',
            'Moose Toys Shopkins Real Littles 5 Pack',
            'Hot Wheels Monster Trucks 1:24 Scale Truck',
            'Hot Wheels Track Builder Stunt Box',
            'Hot Wheels Race Ace Transporter',
            'Hot Wheels Ultimate Garage',
            'Hot Wheels 50th Anniversary Collectible Car',
            'Melissa & Doug Play Money Set',
            'Melissa & Doug Wooden Car Set',
            'Melissa & Doug Pizza Party Game',
            'Melissa & Doug Slice & Bake Cookie Set',
            'Melissa & Doug Wooden Toy Grocery Store',
            'Playmobil City Action Police Station',
            'Playmobil Advent Calendar Christmas in the Park',
            'Playmobil Advent Calendar Farm',
            'Playmobil City Life Restaurant',
            'Playmobil Family Fun Picnic',
            'Fisher-Price Little People Disney Princess Songs Palace',
            'Fisher-Price Imaginext DC Super Friends Batmobile',
            'Fisher-Price Laugh & Learn Smart Stages Puppy',
            'Fisher-Price Little People A to Z Animal Rescue',
            'Fisher-Price Disney Pixar Toy Story Forky’s Adventure',
            'Calico Critters Town Series Red Roof Cozy Cottage',
            'Calico Critters Baby Ferris Wheel',
            'Calico Critters Grand Department Store',
            'Calico Critters Family Camper Van',
            'Calico Critters Adventure Treehouse',
            'TOMY John Deere Sandbox Vehicle Set',
            'TOMY Thomas & Friends Super Station',
            'TOMY Toomies Toot-Toot Drivers Police Car',
            'TOMY Toomies Hide & Squeak Eggs',
            'TOMY Aquadoodle Mini Mat',
            'Hape All-in-One Wooden Toy Kitchen',
            'Hape Eco-Friendly Wooden Dollhouse',
            'Hape Wooden Marble Run with Accessories',
            'Hape Craft & Create Activity Center',
            'Hape Wooden Toy Animal Puzzle',
            'Melissa & Doug Wooden Take-Along Doorbell House',
            'Melissa & Doug Wooden Animal Magnets',
            'Melissa & Doug Wooden Shape Sorting Cube',
            'Melissa & Doug Magnetic Wooden Fishing Game',
            'Melissa & Doug Pounding Bench',
            'Fisher-Price Little People Big Animal Zoo',
            'Fisher-Price Laugh & Learn Sweet Manners Tea Set',
            'Fisher-Price Imaginext Super Friends Batcave',
            'Fisher-Price Little People A to Z Learning Zoo',
            'Fisher-Price Laugh & Learn Puppy’s Remote',
            'VTech Baby’s Learning Laptop',
            'VTech Toot-Toot Drivers Fire Station',
            'VTech Touch and Learn Activity Desk Deluxe',
            'VTech Smart Shots Sports Center',
            'VTech Smart Animal Seek & Find Book',
            'LEGO City Fire Station Building Kit',
            'LEGO Friends Mia’s Horse Trailer',
            'LEGO Ninjago Kai’s Fire Dragon',
            'LEGO Creator 3-in-1 Treehouse',
            'LEGO Technic Lamborghini Sián FKP 37',
            'Hot Wheels Track Builder System Stunt Box',
            'Hot Wheels City Ultimate Garage Playset',
            'Hot Wheels Monster Trucks Bone Shaker',
            'Hot Wheels Stunt and Go Track Set',
            'Hot Wheels Ultimate Vehicle Set',
            'Playmobil 1.2.3 My First Bus',
            'Playmobil City Life Family House',
            'Playmobil Adventure Camp Tree House',
            'Playmobil Pirate Ship',
            'Playmobil Zoo with Animals',
            'Schleich Farm World Horse Club Set',
            'Schleich Wild Life Elephants Figure',
            'Schleich Dinosaurs Brachiosaurus',
            'Schleich Horse Club Riding School',
            'Schleich Eldrador Creatures Stone Monster',
            'Calico Critters Cozy Cottage Starter Home',
            'Calico Critters Red Roof Family Home',
            'Calico Critters Sweets Bakery',
            'Calico Critters Adventure Treehouse',
            'Calico Critters Family Camper Van',
            'TOMY Thomas & Friends TrackMaster Troublesome Trucks',
            'TOMY Toomies Sort & Pop Spinning UFO',
            'TOMY John Deere Sandbox Vehicle Set',
            'TOMY Lamaze Clip & Go Freddie the Firefly',
            'TOMY Toomies Animal Sorting House',
            'Spin Master Kinetic Sand 3 lbs',
            'Spin Master Rubik’s Cube',
            'Spin Master Air Hogs DR1 Mini Racing Drone',
            'Spin Master Hatchimals CollEGGtibles',
            'Spin Master Paw Patrol Mission Cruiser',
            'Fisher-Price Laugh & Learn Smart Stages Puppy',
            'Fisher-Price Imaginext DC Super Friends Batmobile',
            'Fisher-Price Little People Big Animal Zoo',
            'Fisher-Price Laugh & Learn Smart Stages Chair',
            'Fisher-Price Little People A to Z Animal Rescue',
            'Hasbro Monopoly Junior Game',
            'Hasbro Twister Game',
            'Hasbro Connect 4 Game',
            'Hasbro Jenga Classic Game',
            'Hasbro Trouble Game',
            'Crayola Washable Glitter Dots',
            'Crayola Marker Airbrush Set',
            'Crayola Color Wonder Mess-Free Art Set',
            'Crayola Modeling Clay Set',
            'Crayola Inspiration Art Case',
            'Step2 Fun with Friends Playhouse',
            'Step2 Play & Shade Pool',
            'Step2 Naturally Playful Sand & Water Table',
            'Step2 Cozy Coupe Ride-On',
            'Step2 All-Around Playtime Patio with Canopy',
            'L.O.L. Surprise! OMG Fashion Dolls',
            'L.O.L. Surprise! Hairgoals Series',
            'L.O.L. Surprise! Clubhouse Playset',
            'L.O.L. Surprise! Winter Disco Ball',
            'L.O.L. Surprise! All-Star B.B.s Doll',
            'Moose Toys Little Live Pets Unicorn',
            'Moose Toys Scruff-a-Luvs Real Rescue',
            'Moose Toys Real Littles Shopkins',
            'Moose Toys Heroes of Goo Jit Zu - Superhero Edition',
            'Moose Toys Shopkins Real Littles 5 Pack',
            'HEXBUG Nano with Habitat Set',
            'HEXBUG VEX Robotics Building Set',
            'HEXBUG BattleBots Rival Doombah',
            'HEXBUG VEX Robotics Construction Zone',
            'HEXBUG Scarab Robot',
            'TOMY John Deere Big Scoop Dump Truck',
            'TOMY Toomies Toot-Toot Drivers Police Car',
            'TOMY Aquadoodle Magic Mat',
            'TOMY Lamaze Freddie the Firefly',
            'TOMY Gearation Gear Building Set',
            'Brio Classic Railway Starter Set',
            'Brio My First Railway Starter Set',
            'Brio Push-Along Dog',
            'Brio Adventure Railway Set',
            'Brio My First Take Along Train Set',
            'KidKraft Deluxe Activity Cube',
            'KidKraft Superhero Play Set',
            'KidKraft Pirate Ship Play Set',
            'KidKraft Firehouse Play Set',
            'KidKraft Fairy-tale Castle Play Set',
            'Hape Create & Learn Music Set',
            'Hape Piano Play and Learn',
            'Hape Wooden Kids Maracas',
            'Hape First Play Rainbow Xylophone',
            'Hape Musical Rainbow Stacker',
            'LEGO Disney Princess Belle’s Castle',
            'LEGO Star Wars Millennium Falcon',
            'LEGO Ninjago Legacy Kai’s Fire Dragon',
            'LEGO Friends Emma’s Art Studio',
            'LEGO City Monster Truck',
            'Moose Toys Little Live Pets Light Up Unicorn',
            'Moose Toys Scruff-a-Luvs Real Rescue',
            'Moose Toys Real Littles Shopkins',
            'Moose Toys Heroes of Goo Jit Zu - Superhero Edition',
            'Moose Toys Shopkins Real Littles 5 Pack',
            'Hot Wheels Monster Trucks 1:24 Scale Truck',
            'Hot Wheels Track Builder Stunt Box',
            'Hot Wheels Race Ace Transporter',
            'Hot Wheels Ultimate Garage',
            'Hot Wheels 50th Anniversary Collectible Car',
            'Melissa & Doug Play Money Set',
            'Melissa & Doug Wooden Car Set',
            'Melissa & Doug Pizza Party Game',
            'Melissa & Doug Slice & Bake Cookie Set',
            'Melissa & Doug Wooden Toy Grocery Store',
            'Playmobil City Action Police Station',
            'Playmobil Advent Calendar Christmas in the Park',
            'Playmobil Advent Calendar Farm',
            'Playmobil City Life Restaurant',
            'Playmobil Family Fun Picnic',
            'Fisher-Price Little People Disney Princess Songs Palace',
            'Fisher-Price Imaginext Dinosaurs T-Rex',
            'Fisher-Price Laugh & Learn Smart Stages Puppy',
            'Fisher-Price Little People Big Helpers Home',
            'Fisher-Price Little People A to Z Animal Rescue',
            'Calico Critters Town Series Red Roof Cozy Cottage',
            'Calico Critters Baby Ferris Wheel',
            'Calico Critters Grand Department Store',
            'Calico Critters Family Camper Van',
            'Calico Critters Adventure Treehouse',
            'Calico Critters Sweets Bakery',
            'Calico Critters Cozy Cottage Starter Home',
            'Calico Critters Red Roof Family Home',
            'Calico Critters Horse Club Riding School',
            'Calico Critters Zoo with Animals',
            'LEGO City Space Mars Research Shuttle',
            'LEGO Technic Remote-Controlled Stunt Racer',
            'LEGO Friends Heartlake City Park Café',
            'LEGO Harry Potter Hogwarts Express',
            'LEGO Architecture London Skyline',
            'LEGO Creator Expert Roller Coaster',
            'Hot Wheels Monster Trucks Tiger Shark',
            'Hot Wheels City T-Rex Rampage',
            'Hot Wheels Track Builder Vertical Launch Kit',
            'Hot Wheels Car Culture Circuit Legends',
            'Playmobil Country Horse Farm',
            'Playmobil Pirates Skull Pirate Ship',
            'Playmobil City Action Police Car',
            'Playmobil Magic Crystal Palace',
            'Playmobil Dollhouse Cozy Family Home',
            'Schleich Bayala Unicorn Mare',
            'Schleich Farm World Starter Set',
            'Schleich Wild Life Animal Rescue',
            'Schleich Horse Club Hannah’s Guest Horses',
            'Schleich Dinosaurs Tyrannosaurus Rex',
            'Calico Critters Nursery Friends',
            'Calico Critters Baby Castle Playground',
            'Calico Critters Town Girl Series',
            'Calico Critters Deluxe Celebration Home',
            'Calico Critters Sunshine Nursery Bus',
            'TOMY Toomies Hide & Squeak Eggs',
            'TOMY John Deere Tractor & Wagon',
            'TOMY Foam Cone Factory',
            'TOMY Toomies Bubble Blast Train',
            'TOMY Push & Go Plane',
            'Spin Master Bakugan Starter Pack',
            'Spin Master Hatchimals Pixies',
            'Spin Master Air Hogs Gravitor',
            'Spin Master Cool Maker Go Glam Nail Stamper',
            'Spin Master Monster Jam Megalodon',
            'Fisher-Price Linkimals Smooth Moves Sloth',
            'Fisher-Price Thomas & Friends TrackMaster',
            'Fisher-Price Dance & Move BeatBo',
            'Fisher-Price Think & Learn Rocktopus',
            'Fisher-Price Little People Helpful Neighbors',
            'Hasbro Nerf Elite 2.0 Commander RD-6 Blaster',
            'Hasbro Play-Doh Kitchen Creations Magical Oven',
            'Hasbro Baby Alive Real As Can Be Baby',
            'Hasbro Star Wars The Mandalorian The Child',
            'Hasbro My Little Pony Rainbow Road Trip',
            'Crayola Scribble Scrubbie Pets',
            'Crayola Washable Kids Paint Set',
            'Crayola Colored Pencils Adult Coloring Set',
            'Crayola Silly Scents Markers',
            'Crayola Glow Fusion Marker Light Board',
            'Step2 Whisper Ride II Ride-On Push Car',
            'Step2 Naturally Playful Sand Table',
            'Step2 Rain Showers Splash Pond Water Table',
            'Step2 Creative Projects Table',
            'Step2 Sit & Play Picnic Table with Umbrella',
            'L.O.L. Surprise! Remix 4-in-1 Plane',
            'L.O.L. Surprise! O.M.G. Remix Super Surprise',
            'L.O.L. Surprise! Interactive Live Surprise',
            'L.O.L. Surprise! OMG House of Surprises',
            'L.O.L. Surprise! Winter Disco Chalet',
            'Moose Toys Kindi Kids Snack Time Friends',
            'Moose Toys Treasure X Sunken Gold',
            'Moose Toys Heroes of Goo Jit Zu Dino Power',
            'Moose Toys Little Live Pets Lil’ Dippers',
            'Moose Toys Real Littles Micro Mart',
            'HEXBUG BattleBots Arena Pro',
            'HEXBUG Nano Flash',
            'HEXBUG VEX Robotics Hexcalator',
            'HEXBUG Ring Racer',
            'HEXBUG Dragon',
            'TOMY Toomies Bubble Blast Train',
            'TOMY Toomies Sort & Spin UFO',
            'TOMY John Deere Ride On Tractor',
            'TOMY Aquadoodle Classic Colour Doodle Mat',
            'TOMY Toomies Musical Stack & Ball Game',
            'Brio World Travel Train Set',
            'Brio Rescue Emergency Set',
            'Brio Airport with Control Tower',
            'Brio Cargo Harbor Set',
            'Brio Lumber Loading Wagon',
            'KidKraft Uptown Espresso Kitchen',
            'KidKraft Majestic Mansion Dollhouse',
            'KidKraft Let’s Cook Wooden Play Kitchen',
            'KidKraft Adventure Bound Play Set',
            'KidKraft Disney Princess Dance & Dream Dollhouse',
            'Hape Quadrilla Wooden Marble Run Construction',
            'Hape Gourmet Kitchen Starter Play Set',
            'Hape Pound & Tap Bench with Slide Out Xylophone',
            'Hape Fix It Kid’s Wooden Tool Box',
            'Hape Wooden Doll House Furniture Master Bedroom',
            'LEGO Creator 3in1 Deep Sea Creatures',
            'LEGO Classic Creative Bricks',
            'LEGO DOTS Creative Picture Frames',
            'LEGO Ninjago Legacy Fire Dragon Attack',
            'LEGO Marvel Avengers Iron Man Hulkbuster',
            'LEGO Disney Frozen II Elsa’s Jewelry Box',
            'LEGO Technic Catamaran',
            'LEGO Speed Champions Lamborghini',
            'LEGO Architecture Statue of Liberty',
            'LEGO Friends Heartlake City Hair Salon',
            'Hot Wheels id Smart Track Kit',
            'Hot Wheels City Downtown Car Park',
            'Hot Wheels Sky Crash Tower Track Set',
            'Hot Wheels Monster Trucks Demolition Doubles',
            'Hot Wheels Color Shifters Sharkport Showdown',
            'Playmobil Back to the Future DeLorean',
            'Playmobil City Action Police Helicopter',
            'Playmobil Family Fun Camping Adventure',
            'Playmobil Magic Mermaid Cove with Illuminated Dome',
            'Playmobil Dollhouse Deluxe Dollhouse',
            'Schleich Bayala Mermaid Eyela',
            'Schleich Horse Club Sarah’s Camping Adventure',
            'Schleich Dinosaurs Large Skull Trap',
            'Schleich Wild Life Adventure Tree House',
            'Schleich Farm World Rabbit Hutch',
            'Calico Critters Baby Choo-Choo Train',
            'Calico Critters Adventure Treehouse Gift Set',
            'Calico Critters Red Roof Cozy Cottage',
            'Calico Critters Country Tree School',
            'Calico Critters Seaside Cruiser House Boat',
            'TOMY Pic & Pop Ball Blaster',
            'TOMY Gearation Stack & Spin Gears',
            'TOMY John Deere 1st Farming Fun',
            'TOMY Toomies Spin & Drop Ducky',
            'TOMY Stomp & Roar Dinosaur',
            'Spin Master Wizarding World Harry Potter Invisibility Cloak',
            'Spin Master Present Pets Glitter Puppy',
            'Spin Master PAW Patrol Dino Patroller',
            'Spin Master Hatchimals Pixies Crystal Flyers',
            'Spin Master Monster Jam Official Megalodon Storm',
            'Fisher-Price Laugh & Learn Smart Stages Tablet',
            'Fisher-Price Linkimals Light-Up & Learn Owl',
            'Fisher-Price Dance & Groove Rockit',
            'Fisher-Price Little People Share & Care Safari',
            'Fisher-Price Smart Stages Scooter',
            'Hasbro Star Wars Galactic Heroes Millennium Falcon',
            'Hasbro Marvel Legends Series Spider-Man',
            'Hasbro Play-Doh Trolls World Tour Set',
            'Hasbro Baby Alive Magical Mixer Baby',
            'Hasbro My Little Pony Friendship is Magic Collection',
            'Crayola Light-Up Tracing Pad',
            'Crayola Spin & Spiral Art Station',
            'Crayola Washable Sidewalk Chalk',
            'Crayola Take Note Erasable Highlighters',
            'Crayola Fine Line Markers Adult Coloring',
            'Step2 All Around Easel for Two',
            'Step2 Rain Showers Splash Pond Water Table',
            'Step2 Naturally Playful Sand Table',
            'Step2 Fun with Friends Kitchen',
            'Step2 Best Chef’s Kitchen Set',
            'L.O.L. Surprise! Big B.B. (Big Baby)',
            'L.O.L. Surprise! Arcade Heroes',
            'L.O.L. Surprise! Boys Series 3',
            'L.O.L. Surprise! OMG Lights Series',
            'L.O.L. Surprise! Lils Winter Disco',
            'Moose Toys Goo Jit Zu Galaxy Attack',
            'Moose Toys Little Live Rainglow Unicorn Vet Set',
            'Moose Toys Treasure X Aliens Dissection Kit',
            'Moose Toys Kindi Kids Fun Time Friends',
            'Moose Toys Real Littles Handbags',
            'HEXBUG BattleBots Rivals Minotaur & Tombstone',
            'HEXBUG Nano Nitro Slingshot',
            'HEXBUG VEX Robotics Crossbow',
            'HEXBUG Ring Racer with Stunt Park',
            'HEXBUG Scarab XL',
            'TOMY Toomies Jurassic World Pop Up Dino',
            'TOMY Toomies Bath Pipes',
            'TOMY John Deere 15" Big Scoop Dump Truck',
            'TOMY Aquadoodle Classic Colour Doodle Mat',
            'TOMY Toomies Bubble & Bake Bathtub Bakery',
            'Brio World Cargo Train Set',
            'Brio Police Station Playset',
            'Brio Adventure Tunnel',
            'Brio Builder Construction Set',
            'Brio Rescue Firefighter Helicopter',
            'KidKraft Waterfall Mountain Train Set',
            'KidKraft Annabelle Dollhouse',
            'KidKraft Chelsea Doll Cottage with Furniture',
            'KidKraft Disney Frozen Ice Castle Dollhouse',
            'KidKraft Wooden Play Kitchen with Lights & Sounds',
            'Hape Quadrilla Vertigo Marble Run',
            'Hape Multi-Activity Play Table',
            'Hape Shape Sorter Xylophone',
            'Hape Wooden Toy Train Set',
            'Hape Doll Family Mansion',
            'LEGO Technic Land Rover Defender',
            'LEGO Creator 3in1 Dune Buggy',
            'LEGO Friends Heartlake City Airplane',
            'LEGO Ninjago Skull Sorcerer’s Dungeons',
            'LEGO Disney Princess Ariel’s Seaside Castle',
            'LEGO Architecture Empire State Building',
            'LEGO City Main Square',
            'LEGO Marvel Spider-Man Venomaurus Ambush',
            'LEGO DOTS Bracelet Kit',
            'LEGO Classic Large Creative Brick Box',
            'Hot Wheels Monster Trucks Race Ace',
            'Hot Wheels City Robo Shark Attack',
            'Hot Wheels Track Builder Unlimited',
            'Hot Wheels Car Culture Team Transport',
            'Hot Wheels City Super Spin Tire Shop',
            'Playmobil City Action Police Headquarters',
            'Playmobil Family Fun Aquarium',
            'Playmobil Magic Crystal Gate to the Winter World',
            'Playmobil Dollhouse Kitchen',
            'Playmobil Country Pony Farm',
            'Schleich Horse Club Sofia’s Beauties Mobile Vet',
            'Schleich Dinosaurs Volcano',
            'Schleich Wild Life Ranger Adventure Station',
            'Schleich Farm World Animal Nursery',
            'Schleich Bayala Flower Dragon',
            'Calico Critters Baby Discovery Forest',
            'Calico Critters Baby Ferris Wheel',
            'Calico Critters Town Grand Manor Gift Set',
            'Calico Critters Adventure Treehouse Gift Set',
            'Calico Critters Baby Amusement Park',
            'TOMY Toomies Rocket Ship',
            'TOMY Toomies Dinosaur Train',
            'TOMY John Deere Remote Control Johnny Tractor',
            'TOMY Aquadoodle Neon Classic',
            'TOMY Toomies Sort & Pop Spinning UFO',
            'Spin Master Wizarding World Harry Potter Hedwig',
            'Spin Master Present Pets Princess Puppy',
            'Spin Master PAW Patrol Adventure Bay Rescue Way',
            'Spin Master Hatchimals Pixies Riders',
            'Spin Master Monster Jam Megalodon Storm',
            'Fisher-Price Laugh & Learn Smart Stages Chair',
            'Fisher-Price Linkimals Cool Beats Penguin',
            'Fisher-Price Dance & Move BeatBelle',
            'Fisher-Price Little People Caring for Animals Farm',
            'Fisher-Price Smart Stages Puppy',
            'Hasbro Star Wars The Mandalorian Darksaber',
            'Hasbro Marvel Legends Series Iron Man',
            'Hasbro Play-Doh Kitchen Creations Drizzy Ice Cream Playset',
            'Hasbro Baby Alive Snackin’ Lily',
            'Hasbro My Little Pony Equestria Girls Minis',
            'Crayola Light-Up Tracing Pad Blue',
            'Crayola Silly Scents Twistables Crayons',
            'Crayola Washable Window Markers',
            'Crayola Take Note Permanent Markers',
            'Crayola Drawing Chalk Multicolor',
            'Step2 Great Gourmet Kitchen Set',
            'Step2 Rain Showers & Unicorns Water Table',
            'Step2 Naturally Playful Picnic Table with Umbrella',
            'Step2 Fun with Friends Kitchen',
            'Step2 Adventure Lodge Play Center',
            'L.O.L. Surprise! Big B.B. (Big Baby)',
            'L.O.L. Surprise! OMG Remix Fashion Dolls',
            'L.O.L. Surprise! Boys Arcade Heroes',
            'L.O.L. Surprise! OMG Series 3',
            'L.O.L. Surprise! Winter Disco Chalet',
            'Moose Toys Treasure X Kings Gold',
            'Moose Toys Little Live Pets My Pet Pig',
            'Moose Toys Heroes of Goo Jit Zu Dino Power',
            'Moose Toys Kindi Kids Fun Time Friends',
            'Moose Toys Real Littles Handbags',
            'HEXBUG BattleBots Arena Pro',
            'HEXBUG Nano Nitro Slingshot',
            'HEXBUG VEX Robotics Crossbow',
            'HEXBUG Ring Racer with Stunt Park',
            'HEXBUG Scarab XL',
            'TOMY Toomies Jurassic World Pop Up Dino',
            'TOMY Toomies Bath Pipes',
            'TOMY John Deere 15" Big Scoop Dump Truck',
            'TOMY Aquadoodle Classic Colour Doodle Mat',
            'TOMY Toomies Bubble & Bake Bathtub Bakery',
            'Brio World Cargo Train Set',
            'Brio Police Station Playset',
            'Brio Adventure Tunnel',
            'Brio Builder Construction Set',
            'Brio Rescue Firefighter Helicopter',
            'KidKraft Waterfall Mountain Train Set',
            'KidKraft Annabelle Dollhouse',
            'KidKraft Chelsea Doll Cottage with Furniture',
            'KidKraft Disney Frozen Ice Castle Dollhouse',
            'KidKraft Wooden Play Kitchen with Lights & Sounds',
            'Hape Quadrilla Vertigo Marble Run',
            'Hape Multi-Activity Play Table',
            'Hape Shape Sorter Xylophone',
            'Hape Wooden Toy Train Set',
            'Hape Doll Family Mansion',
            'LEGO Technic Land Rover Defender',
            'LEGO Creator 3in1 Dune Buggy',
            'LEGO Friends Heartlake City Airplane',
            'LEGO Ninjago Skull Sorcerer’s Dungeons',
            'LEGO Disney Princess Ariel’s Seaside Castle',
            'LEGO Architecture Empire State Building',
            'LEGO City Main Square',
            'LEGO Marvel Spider-Man Venomaurus Ambush',
            'LEGO DOTS Bracelet Kit',
            'LEGO Classic Large Creative Brick Box',
            'Hot Wheels Monster Trucks Race Ace',
            'Hot Wheels City Robo Shark Attack',
            'Hot Wheels Track Builder Unlimited',
            'Hot Wheels Car Culture Team Transport',
            'Hot Wheels City Super Spin Tire Shop',
            'Playmobil City Action Police Headquarters',
            'Playmobil Family Fun Aquarium',
            'Playmobil Magic Crystal Gate to the Winter World',
            'Playmobil Dollhouse Kitchen',
            'Playmobil Country Pony Farm',
            'Schleich Horse Club Sofia’s Beauties Mobile Vet',
            'Schleich Dinosaurs Volcano',
            'Schleich Wild Life Ranger Adventure Station',
            'Schleich Farm World Animal Nursery',
            'Schleich Bayala Flower Dragon',
            'Calico Critters Baby Discovery Forest',
            'Calico Critters Baby Ferris Wheel',
            'Calico Critters Town Grand Manor Gift Set',
            'Calico Critters Adventure Treehouse Gift Set',
            'Calico Critters Baby Amusement Park',
            'TOMY Toomies Rocket Ship',
            'TOMY Toomies Dinosaur Train',
            'TOMY John Deere Remote Control Johnny Tractor',
            'TOMY Aquadoodle Neon Classic',
            'TOMY Toomies Sort & Pop Spinning UFO',
            'Spin Master Wizarding World Harry Potter Hedwig',
            'Spin Master Present Pets Princess Puppy',
            'Spin Master PAW Patrol Adventure Bay Rescue Way',
            'Spin Master Hatchimals Pixies Riders',
            'Spin Master Monster Jam Megalodon Storm',
            'Fisher-Price Laugh & Learn Smart Stages Chair',
            'Fisher-Price Linkimals Cool Beats Penguin',
            'Fisher-Price Dance & Move BeatBelle',
            'Fisher-Price Little People Caring for Animals Farm',
            'Fisher-Price Smart Stages Puppy',
            'Hasbro Star Wars The Mandalorian Darksaber',
            'Hasbro Marvel Legends Series Iron Man',
            'Hasbro Play-Doh Kitchen Creations Drizzy Ice Cream Playset',
            'Hasbro Baby Alive Snackin’ Lily',
            'Hasbro My Little Pony Equestria Girls Minis',
            'Crayola Light-Up Tracing Pad Blue',
            'Crayola Silly Scents Twistables Crayons',
            'Crayola Washable Window Markers',
            'Crayola Take Note Permanent Markers',
            'Crayola Drawing Chalk Multicolor',
            'Step2 Great Gourmet Kitchen Set',
            'Step2 Rain Showers & Unicorns Water Table',
            'Step2 Naturally Playful Picnic Table with Umbrella',
            'Step2 Fun with Friends Kitchen',
            'Step2 Adventure Lodge Play Center',
            'L.O.L. Surprise! Big B.B. (Big Baby)',
            'L.O.L. Surprise! OMG Remix Fashion Dolls',
            'L.O.L. Surprise! Boys Arcade Heroes',
            'L.O.L. Surprise! OMG Series 3',
            'L.O.L. Surprise! Winter Disco Chalet',
            'Moose Toys Treasure X Kings Gold',
            'Moose Toys Little Live Pets My Pet Pig',
            'Moose Toys Heroes of Goo Jit Zu Dino Power',
            'Moose Toys Kindi Kids Fun Time Friends',
            'Moose Toys Real Littles Handbags',
            'HEXBUG BattleBots Arena Pro',
            'HEXBUG Nano Nitro Slingshot',
            'HEXBUG VEX Robotics Crossbow',
            'HEXBUG Ring Racer with Stunt Park',
            'HEXBUG Scarab XL',
            'TOMY Toomies Jurassic World Pop Up Dino',
            'TOMY Toomies Bath Pipes',
            'TOMY John Deere 15" Big Scoop Dump Truck',
            'TOMY Aquadoodle Classic Colour Doodle Mat',
            'TOMY Toomies Bubble & Bake Bathtub Bakery',
            'Brio World Cargo Train Set',
            'Brio Police Station Playset',
            'Brio Adventure Tunnel',
            'Brio Builder Construction Set',
            'Brio Rescue Firefighter Helicopter',
            'KidKraft Waterfall Mountain Train Set',
            'KidKraft Annabelle Dollhouse',
            'KidKraft Chelsea Doll Cottage with Furniture',
            'KidKraft Disney Frozen Ice Castle Dollhouse'
        ];
    }
}
